### ISSUE TITLE
cuda runtime errror

### ISSUE THREAD

**Issue by 1csu** [jwyang/faster-rcnn.pytorch#244]
such error occurred:
File "trainval_net.py", line 214, in <module>
    im_data = im_data.cuda()
  File "/home/csu/anaconda3/lib/python3.6/site-packages/torch/_utils.py", line 69, in _cuda
    return new_type(self.size()).copy_(self, async)
  File "/home/csu/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 384, in _lazy_new
    _lazy_init()
  File "/home/csu/anaconda3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 142, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /pytorch/torch/lib/THC/THCGeneral.c:70
I have installed cuda8.0,but this issue happened,I hope someone can give me some advice,thanks a lot.

**Comment by Worulz** [comment]
@1csu 
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected

The error is probably due to a CUDA path error. you can add it to your bash profile and it should fix the problem.

**Comment by 1csu** [comment]
Wed Jul 18 09:02:10 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.67                 Driver Version: 390.67                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 105...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   45C    P3    N/A /  N/A |    190MiB /  4042MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1123      G   /usr/lib/xorg/Xorg                           126MiB |
|    0      1706      G   compiz                                        42MiB |
|    0      1827      G   fcitx-qimpanel                                 4MiB |
|    0      2850      G   ...passed-by-fd --v8-snapshot-passed-by-fd    16MiB |
+-----------------------------------------------------------------------------+

**Comment by 1csu** [comment]
@jwyang ,run"nvidia-smi",show as follows:
Wed Jul 18 09:02:10 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.67                 Driver Version: 390.67                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 105...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   45C    P3    N/A /  N/A |    190MiB /  4042MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1123      G   /usr/lib/xorg/Xorg                           126MiB |
|    0      1706      G   compiz                                        42MiB |
|    0      1827      G   fcitx-qimpanel                                 4MiB |
|    0      2850      G   ...passed-by-fd --v8-snapshot-passed-by-fd    16MiB |
+-----------------------------------------------------------------------------+
obviously my gpus exists

**Comment by jwyang** [comment]
@1csu it is GTX 1050 (TI), right? Have you ever run pytorch cuda code on it before?

**Comment by 1csu** [comment]
@jwyang ,yes,I have runned pytorch cuda code on it before,and it works well.

**Comment by adamklec** [comment]
I'm seeing the same error on an AWS p2 instance.

**Comment by srp753** [comment]
I am also facing the same issue. @1csu did you find a solution to this?

@jwyang My system has a GPU GeForce GTX 1060 3GB/PCIe/SSE2
snigdha.purohit@u-purohit:~$ nvidia-smi
Fri Jul 20 15:46:56 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   40C    P8     8W / 120W |    812MiB /  3010MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2412      G   /usr/lib/xorg/Xorg                           435MiB |
|    0      3030      G   compiz                                       242MiB |
|    0      3249      G   ...-token=B73B209BDDDB20C19CE1594D76CDC091   128MiB |
|    0     28351      G   unity-control-center                           2MiB |

Mine is 7.5 CUDA and PyTorch installed is CUDA 8 . Can this difference create this problem?

**Comment by jwyang** [comment]
@srp753 , yes i think that is the reason.

**Comment by srp753** [comment]
I ran your code on AWS with CUDA 8.0 and strictly PyTorch 0.3.0 and it works perfectly.
@jwyang Thanks a lot for making this PyTorch code. It is much easier to use and adapt.

Do you have any suggestions for change in architecture to detect small objects?
Do I need to change the FRCNN architecture internally to accomodate detection of small objects(15*15 dimension)?

For now, I have high resolution image of the small object(approx. 25*25) so I am
getting good detections but still your guidance on this will be very helpful.
