### ISSUE TITLE
RunTimeError: cuda runtime error (77) when trying to print the features from RoI Align

### ISSUE THREAD

**Issue by hguosc** [jwyang/faster-rcnn.pytorch#250]
What I need now is just the RoI Align.

When I was trying to use the 
`
# after importing RoIAlignAvg
temp = roi_align(feature, pseudo_roi)
print(temp)
`
The error came out:
`RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1518243271935/work/torch/lib/THC/generic/THCTensorCopy.c:70`

Could someone help me with this? Thanks a lot.

**Comment by MengTianjian** [comment]
I encountered the same problem, is it caused by the difference between PyTorch 0.3 and 0.4?

**Comment by sovan-biswas** [comment]
I ran into the same error. However, for me the datatype for 'roi' was torch.FloatTensor. Changing it to torch.cuda.FloatTensor did the trick. 

Guess, one needs to keep track of the datatypes while using the compiled binaries.
